name: test_prep
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.19.0 <=3.5.3"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  get:
  gap: ^3.0.1
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.9
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
